import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadParserCorpusManifestCases } from "../browser_ui_upstream/tests/parser_corpus_manifest_util.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const OUTPUT_PATH = path.join(__dirname, "..", "engine", "tikz_parser_corpus_manifest_data.mbt");

function escapeMoonBitString(value) {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t");
}

function stringifyMaybe(value) {
  if (value === null) {
    return "None";
  }
  return `Some("${escapeMoonBitString(value)}")`;
}

function renderCase(entry) {
  return [
    "    {",
    `      id: "${escapeMoonBitString(entry.id)}",`,
    `      section: "${escapeMoonBitString(entry.section)}",`,
    `      title: "${escapeMoonBitString(entry.title)}",`,
    `      engine_group: "${escapeMoonBitString(entry.engine_group)}",`,
    `      engine_context: ${stringifyMaybe(entry.engine_context)},`,
    `      runtime_expectation: "${escapeMoonBitString(entry.runtime_expectation)}",`,
    `      snippet: "${escapeMoonBitString(entry.snippet)}",`,
    "    },",
  ].join("\n");
}

function renderMoonBit(cases) {
  const renderedCases = cases.map((entry) => renderCase(entry)).join("\n");
  return [
    "/// Auto-generated by scripts/sync_parser_corpus_manifest.mjs.",
    "/// Source of truth: browser_ui_upstream/tests/parser_corpus_manifest.json + parser.tex.",
    "/// DO NOT EDIT MANUALLY.",
    "",
    "pub struct TikzParserCorpusManifestCase {",
    "  id : String",
    "  section : String",
    "  title : String",
    "  engine_group : String",
    "  engine_context : String?",
    "  runtime_expectation : String",
    "  snippet : String",
    "}",
    "",
    "///|",
    "pub fn tikz_parser_corpus_manifest_cases() -> Array[TikzParserCorpusManifestCase] {",
    "  [",
    renderedCases,
    "  ]",
    "}",
    "",
  ].join("\n");
}

function run() {
  const cases = loadParserCorpusManifestCases();
  const content = renderMoonBit(cases);
  writeFileSync(OUTPUT_PATH, content, "utf8");
  console.log(`synced parser corpus manifest: ${cases.length} cases -> ${OUTPUT_PATH}`);
}

run();
